---
- name: config webservers
  hosts: web
  tasks:
    - name: install web pkgs
      yum:
        name:
          - httpd
          - php
          - php-mysql
        state: present

    - name: config web service
      service:
        name: httpd
        state: started
        enabled: yes

- name: config db
  hosts: db
  tasks:
    - name:
     yum:
        name: mariadb-server
        state: present

    - name: config db service
      service:
        name: mariadb
        state: started
        enabled: yes
                                                              31,5         底端
